### ISSUE TITLE
Session allows to add iteration to open list with absent active person

### ISSUE THREAD

**Issue by IevhenIkonnykov** [RHEAGROUP/CDP4-SDK-Community-Edition#55]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-SDK
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
CDP4DAL.Session lines 754-759
            var activeParticipant = ((EngineeringModel)iteration.Container).EngineeringModelSetup.Participant.Where(p => p.Person == this.ActivePerson).SingleOrDefault();

            if (activeParticipant == null)
            {
                throw new InvalidOperationException("The iteration does not have an active participant associated.");
            }

A call of .SingleOrDefault() never returns null, that passes a null check. This should not be allowed.

### Steps to Reproduce
See source code. CDP4Dal.NetCore.Tests. SessionTestFixture.VerifyThatReadIterationWorks passes, but should not, because there is not an active person in a session.

### System Configuration
Does not matter.

- CDP4 version:
  - [ ] CDP4Common:         
  - [ ] CDP4JsonSerializer: 
  - [ ] CDP4Dal:            
  - [ ] CDP4JsonFileDal:    
  - [ ] CDP4ServicesDal:    
  - [ ] CDP4WspDal:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by alexatrhea** [comment]
should be
```
var activeParticipant = ((EngineeringModel)iteration.Container).EngineeringModelSetup.Participant.SingleOrDefault(p => p.Person == this.ActivePerson);
```
probably

**Comment by samatrhea** [comment]
@alexatrhea i agree with you that the LINQ query sould be simplified they way you propose. ut @IevhenIkonnykov i am running the unit test and debugging it and i think (with or without @alexatrhea 's LINQ improvement) that it is doing what it is supposed to do. While looking at the code and also debugging (stepping through it) i see that the `ActivePerson` property is computed as expected (see the Session class on line 140) and matches the person that set is on the Participant on line 497 of the mentioned CDP4Dal.Tests.VerifyThatReadIterationWorks() test method

I think the code is correct.

**Comment by IevhenIkonnykov** [comment]
When I debug I see the following:
line 498 - participant is added to modelsetup and its person property is set to null that was returned from this.session.ActivePerson
line 519 is executed and it leads over some code to Session line 754 where p => p.Person == this.ActivePerson returns true when both sides are null and returns a participant. 
I think it is a flaw that a participant might have a null person and because active person is null then it is okay to open an iteration.
 In Java I use equals where null.equals(null) => false which in this case is more appropriate, because we actually trying to compare real objects and not nulls.
Please take a look again and let me know whether I am mistaken.
If you see the Session class on line 140 you may see that it is not possible to get a person, because there is not such an object in the cache.

**Comment by samatrhea** [comment]
@IevhenIkonnykov  I get your point about the fact that the logic may be incorrect when both sides are null, so this can be fixed with an extra, just thinking where this check should take place. But, i am a bit confused why on your end debugging the C# code yields different results then when i do it.

Looking at https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/89eb7e4414f4d746193e058e16d6c3af5825d4bd/CDP4Dal.NetCore.Tests/SessionTestFixture.cs#L96 and https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/89eb7e4414f4d746193e058e16d6c3af5825d4bd/CDP4Dal.NetCore.Tests/SessionTestFixture.cs#L117 i see that a `Person` object is created and a `Credentials` object with a corresponding ShortName on the bases of which the ActivePerson is determined in https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/89eb7e4414f4d746193e058e16d6c3af5825d4bd/CDP4Dal/Session.cs#L149

In the test the participant is created with the Person property set https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/blob/89eb7e4414f4d746193e058e16d6c3af5825d4bd/CDP4Dal.NetCore.Tests/SessionTestFixture.cs#L497. 

 can you let me know you have similar code?

**Comment by samatrhea** [comment]
@IevhenIkonnykov and @alexatrhea can you have a look at https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/pull/56 whether this is a step in the right direction?

**Comment by samatrhea** [comment]
i've been thinking about this issue a bit more and i think we should set the ActivePerson when we call open, if this cannot be set, that means that the Person object of the user that is access the service is not being returned, which should not happen. Therefore i propose to update the logic in the `Open` method and throw an exception (IncompleteModelException). What do you guys think about this approach?
